package com.moonlight.poo.forms;

import com.moonlight.poo.classes.Infraction;
import com.moonlight.poo.classes.Infractions;
import javax.swing.JOptionPane;

/**
 *
 * @author Mar_Zamudio
 */
public class JDInfraction extends javax.swing.JDialog {
    Infractions infractions;
    
    public JDInfraction(java.awt.Frame parent, boolean modal, Infractions infractions) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.infractions = infractions;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfFolio = new javax.swing.JTextField();
        jcbCode = new javax.swing.JComboBox<>();
        jtfAmount = new javax.swing.JTextField();
        jbAccept = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 68, 68));
        jLabel1.setText("Folio");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 68, 68));
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 68, 68));
        jLabel3.setText("Monto");

        jtfFolio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfFolio.setForeground(new java.awt.Color(68, 68, 68));
        jtfFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFolioKeyTyped(evt);
            }
        });

        jcbCode.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcbCode.setForeground(new java.awt.Color(68, 68, 68));
        jcbCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jtfAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfAmount.setForeground(new java.awt.Color(68, 68, 68));
        jtfAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAmountKeyTyped(evt);
            }
        });

        jbAccept.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbAccept.setForeground(new java.awt.Color(34, 34, 34));
        jbAccept.setText("Aceptar");
        jbAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAcceptActionPerformed(evt);
            }
        });

        jbCancel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbCancel.setForeground(new java.awt.Color(34, 34, 34));
        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 34, 34));
        jLabel4.setText("Multas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jcbCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfAmount)
                                .addComponent(jtfFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbCode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAcceptActionPerformed
        if (jtfFolio.getText().equals("") || jcbCode.getSelectedIndex() <= 0 || 
                jtfAmount.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Olvido ingresar un valor", "Multas", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        long folio = Long.parseLong(jtfFolio.getText());
        int code = Integer.parseInt(jcbCode.getSelectedItem().toString());
        double amount = Double.parseDouble(jtfAmount.getText());
        
        Infraction infraction = new Infraction(folio, code, amount);
        boolean saved = infractions.add(infraction);
        
        if (saved) {
            JOptionPane.showMessageDialog(this, "Multa registrada con exito");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar la Multa");    
        }
    }//GEN-LAST:event_jbAcceptActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jtfFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFolioKeyTyped
        validateNumbers(evt);
    }//GEN-LAST:event_jtfFolioKeyTyped

    private void jtfAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAmountKeyTyped
        validateNumbers(evt);
    }//GEN-LAST:event_jtfAmountKeyTyped

    private void validateNumbers(java.awt.event.KeyEvent evt) {
        char key = evt.getKeyChar();
        
        if (!Character.isDigit(key)) {
            evt.consume();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbAccept;
    private javax.swing.JButton jbCancel;
    private javax.swing.JComboBox<String> jcbCode;
    private javax.swing.JTextField jtfAmount;
    private javax.swing.JTextField jtfFolio;
    // End of variables declaration//GEN-END:variables
}
